### PR TITLE
Added support for including the attachment for FileInfo type.

### PR DESCRIPTION
**Pull request by kzadorozhnaya**
The issue includes adding the NuGet reference to get the content type mapping. @nvborisenko please check if that works or not.

### CODE REVIEW

**Comment by nvborisenko** [comment]
We have internal class to determine mimetype by file's extension. https://github.com/reportportal/commons-net/blob/f0157908e7c7e6c43923c92b7cdbee9dab6b925f/src/ReportPortal.Shared/MimeTypes/MimeTypeMap.cs#L9

**Comment by Aleh-Yanushkevich** [comment]
I think, that we should have ability to use `FileInfo` not only for _INFO_ log level, but for other levels as well. @kzadorozhnaya, @nvborisenko whould do you think?

**Comment by kzadorozhnaya** [comment]
Log message in case of file not found (or other exception):
image

Log message in case of file is null:
image

Log message in case of file was found and attached:
image

**Comment by nvborisenko** [comment]
Cannot understand why RP UI shows exception as a quote when there is no direct statements about it.

**Comment by kzadorozhnaya** [comment]
> Cannot understand why RP UI shows exception as a quote when there is no direct statements about it.

image

That was incorrect screenshot, I just put the quote while testing, sorry for confusing. Here is the correct one. @nvborisenko

**Review by nvborisenko — APPROVED** [review]

**Pull request merged**
