### PR TITLE
Properly read file content with concurrent consumers

### LINKED ISSUE #144: Impossible upload log4net log file at end of tests execution
Impossible to upload log4net log file from test solution in case if method 
`Context.Launch.Log.Info("Tests.log", new FileInfo(logFile));`

executes in [AfterTestRun] Specflow hook or [[OneTimeTearDown]](https://docs.nunit.org/articles/nunit/writing-tests/attributes/onetimeteardown.html) method. 

image

Reason of this error in method GetLogMessageWithAttachmentFromFileInfo that used File.ReadAllBytes(file.FullName) that throw exception when tried to read file that used by another process.

### PR DESCRIPTION
**Pull request by nvborisenko**
Fixes #144

### CODE REVIEW

**Comment by goblinmaks** [comment]
@nvborisenko Could you please release nuget from this PR to myget?

**Comment by nvborisenko** [comment]
After merging it will be published to MyGet. But before merging let's verify it in different way, just put this piece of code:
```csharp
              using (var fileStream = File.Open(file.FullName, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
              {
                  using (var memoryStream = new MemoryStream())
                  {
                      fileStream.CopyTo(memoryStream);
                      var bytes = memoryStream.ToArray();
                  }
              }
```

**Comment by goblinmaks** [comment]
Works as expected. Thank you for fast fix.

**Comment by nvborisenko** [comment]
Thanks for the verification.

**Pull request merged**
