### PR TITLE
Added a new LaunchReporter constructor

### PR DESCRIPTION
**Pull request by aliaksandrbasau**
Added a new LaunchReporter constructor to be used in cases when we need LaunchReporter for existing launch (e.g. to report results from different computers into single launch)

### CODE REVIEW

**Comment by aliaksandrbasau** [comment]
@nvborisenko I have just noticed that you provided a new example on how to combine several executions into one launch. My approach might be more preferable as it requires less knowledge of `commons` and plugin internals. Please decide whether to keep these changes or not.

**Comment by aliaksandrbasau** [comment]
@nvborisenko How about the following changes? Internals of `LaunchReporter` are hidden. The client code will look like this (for SpecFlow):

```C#
        private static void ReportPortalAddin_BeforeRunStarted(object sender, RunStartedEventArgs e)
        {
            var launchId = SettingsManager.CommonSettings.ReportPortalLaunchId;
            if (launchId.IsNullOrEmpty() == false)
            {
                e.LaunchReporter = new LaunchReporter(e.Service, launchId, DateTime.Now);
                e.Canceled = true;
            }
        }

        private static void ReportPortalAddin_BeforeRunFinished(object sender, RunFinishedEventArgs e)
        {
            var launchId = SettingsManager.CommonSettings.ReportPortalLaunchId;
            if (launchId.IsNullOrEmpty() == false)
            {
                e.Canceled = true;
                e.LaunchReporter.Finish(e.Launch, false, false);
                e.LaunchReporter.FinishTask.Wait();
            }
        }
```

I added a new Finish method with different signature to keep backward compatibility. The method has `finishLaunch` argument that controls whether to finish launch or not. Although I would prefer to have a different method that wouldn't finish launch because in this case `request` and `force` arguments are redundant if `finishLaunch` is `false`. But adding a new Finish method that doesn't have arguments and doesn't finish launch makes even less sense (Finish method that doesn't finish anything).

**Comment by nvborisenko** [comment]
I prefer to keep this library as simple as possible. The purpose of this library is just to send results using multithreading. I agree that to customize the behavior we need know some internal staff. My opinion here is it will hard to manage all variants of behaviors that user wants, this is responsibility of user to manage it. So, let's introduce this kind of functionality on higher level (agent, or user's code).

What we can improve here: document how this library works internally.

**Comment by aliaksandrbasau** [comment]
@nvborisenko I don't think that adding a new constructor that allows you to work with an existing launch will complicate the library. It's a great library and I would want end-users to be able to re-use parts of it without learning too much about it internals.
I only agree about the second part of the solution - finishing launch. It could be made more clear and simple.
I am going to close the PR since it doesn't block me. I was just worried that the class didn't encapsulate its internals enough.

**Pull request closed without merging**
